version: 0.0
os: linux
files:
  - source: build/libs
    destination: /home/ubuntu/pcy-car-reservation-site/build/libs
  - source: /.aws/aws-codedeploy-scripts
    destination: /home/ubuntu/pcy-car-reservation-site/.aws/aws-codedeploy-scripts
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: ./.aws/aws-codedeploy-scripts/stop.sh 
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: ./.aws/aws-codedeploy-scripts/start.sh
      timeout: 60
      runas: ubuntu