spring:
  datasource:
    url: jdbc:mysql://pych-car-database.chqw4geoevgr.ap-northeast-2.rds.amazonaws.com/pych_car_reservation
    username: admin
    password: rlarbghks12
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 기존 데이터가 있을 경우 'create' 대신 'update'를 사용하는 것이 좋습니다.
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug


cloud:
  aws:
    s3:
      bucket: pych-car-reservation-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA44Y6CPFOQ36BVTWS
      secretKey: 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